package com.smartorg.models;

public enum TaskStatus {
	PENDING,
	IN_PROGRESS,
	COMPLETED,
	OVERDUE,
	NOT_STARTED,
	DELAYED,
	NOT_ASSIGNED,
	ASSIGNED,
	NOT_STARTED_ON_TIME,
	STARTED_ON_TIME,
	NOT_COMPLETED_ON_TIME,
	COMPLETED_ON_TIME,
	NOT_STARTED_ON_TIME_AND_NOT_COMPLETED_ON_TIME,
	FAILED;
}
